import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export type IHomePageProps = {
  content: string;
}

const Home: NextPage<IHomePageProps> = (props) => {
  const { content } = props;
  console.log('HomePage');

  return (
    <div className={styles.container}>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {
            content
          }
        </h1>
      <div className={styles.grid}>
        <Link href="/others/products/slug-1">
          <a className={styles.card}>
            <h2>Go to Products - Slug 1 &rarr;</h2>
          </a>
        </Link>
        <Link href="/others/products/slug-2">
          <a className={styles.card}>
            <h2>Go to Products - Slug 2 &rarr;</h2>
          </a>
        </Link>
        <Link href="/others/products/slug-3">
          <a className={styles.card}>
            <h2>Go to Products - Slug 3 &rarr;</h2>
          </a>
        </Link>
      </div>
      </main>

    </div>
  )
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      content: 'Home page',
    } as IHomePageProps,
    notFound: false,
    revalidate: 600 // In seconds
  };
};

export default Home
